In [1]:
import pandas as pd
from imdb import IMDb
import MySQLdb
import numpy as np

ImportError: No module named MySQLdb

In [4]:
pd.concat?

In [2]:
db = MySQLdb.connect("localhost","imdb","imdb","imdb" )
cursor = db.cursor()

In [3]:
sql='''
SELECT 
    `title`.`id`,
    `title`.`title`,
    `name`.`name`,
    `cast_info`.`person_id`,
    `movie_info_idx`.`info` AS `rating`,
    `role_type`.`role`,
    `actor_rating`.`avg_actor_rating` AS `avg_actor_rating`
FROM
    (SELECT 
        `name`.`id`,
            `name`.`name`,
            AVG(`movie_info_idx`.`info`) AS `avg_actor_rating`
    FROM
        `cast_info`, `name`, `role_type`, `title`, `movie_info_idx`
    WHERE
        `cast_info`.`person_id` = `name`.`id`
            AND `role_type`.`id` = `cast_info`.`role_id`
            AND `title`.`id` = `cast_info`.`movie_id`
            AND `title`.`id` = `movie_info_idx`.`movie_id`
            AND `title`.`kind_id` = 1
            AND (`role_type`.`role` = 'actor'
            OR `role_type`.`role` = 'actress')
            AND `title`.`production_year` < 2015
            AND `movie_info_idx`.`info_type_id` = 101
    GROUP BY `name`.`id`) AS `actor_rating`,
    `cast_info`,
    `role_type`,
    `name`,
    `title`
        INNER JOIN
    `movie_info_idx` ON `movie_info_idx`.`movie_id` = `title`.`id`
WHERE
    `title`.`id` = `cast_info`.`movie_id`
        AND `movie_info_idx`.`info_type_id` = 101
        AND `role_type`.`id` = `cast_info`.`role_id`
        AND `name`.`id` = `cast_info`.`person_id`
        AND ((`role_type`.`role` = 'actor'
        AND `cast_info`.`nr_order` < 5)
        OR (`role_type`.`role` = 'actress'
        AND `cast_info`.`nr_order` < 5)
        OR `role_type`.`role` = 'writer'
        OR `role_type`.`role` = 'director')
        AND `title`.`production_year` < 2016
        AND `title`.`production_year` > 2012
        AND `name`.`id`=`actor_rating`.`id`
ORDER BY `cast_info`.`nr_order`
'''

In [4]:
cursor.execute(sql)
data = list(cursor.fetchall())

In [7]:
movies=pd.DataFrame(data, columns=['movie_id', 'movie_name', 'name', 'person_id','rating', 'role', 'avg_actor_rating'])

In [8]:
movies

,movie_id,movie_name,name,person_id,rating,role,avg_actor_rating
0,2710597,2 Live Crew: Take It Off,2 Live Crew,365,3.2,writer,4.600000
1,2715287,3:00,"A., Sergey",745,7.2,director,7.384375
2,2786494,Anthology of Horror 2,"A., Sergey",745,8.2,director,7.384375
3,2786953,Antologiya uzhasov,"A., Sergey",745,7.2,director,7.384375
4,2815107,Balka Illi,"A., Sergey",745,5.7,director,7.384375
5,2822546,Baykalskiy intsident. Skrytaya ugroza,"A., Sergey",745,6.3,director,7.384375
6,2843706,Bitva za Sevastopol,"A., Sergey",745,7.5,director,7.384375
7,2890915,Cave,"A., Sergey",745,8.2,director,7.384375
8,2892255,Cemetery Legend,"A., Sergey",745,7.3,director,7.384375
9,2996883,Don't Go Into the Woods Alone,"A., Sergey",745,6.6,director,7.384375
10,3009223,Dukh,"A., Sergey",745,7.6,director,7.384375
11,3010295,Dusha,"A., Sergey",745,8.1,director,7.384375
12,3047826,Evidence,"A., Sergey",745,8.4,director,7.384375
13,3205584,Inter Star Wars: The Awaking Force,"A., Sergey",745,7.1,director,7.384375
14,3206617,Interstelar,"A., Sergey",745,6.8,director,7.384375
15,3220979,Jaws 19,"A., Sergey",745,5.7,director,7.384375
16,3256784,Kladbishche zabytykh mertvetsov,"A., Sergey",745,7.9,director,7.384375
17,3261658,Koshmar na Olimpiade. Gibel Sochi,"A., Sergey",745,8.4,director,7.384375
18,3318813,Lestnitsa,"A., Sergey",745,7.6,director,7.384375
19,3339550,Lost in the Woods,"A., Sergey",745,7.8,director,7.384375
20,3438362,Night Visitor,"A., Sergey",745,6.2,director,7.384375
21,3438708,Nightmare in Bratislava,"A., Sergey",745,6.8,director,7.384375
22,3438713,Nightmare in Moscow,"A., Sergey",745,7.6,director,7.384375
23,3438724,Nightmare in Wien,"A., Sergey",745,7.8,director,7.384375
24,3457807,Obitel strakha,"A., Sergey",745,7.5,director,7.384375
25,3478130,Otel mertvetsov,"A., Sergey",745,7.7,director,7.384375
26,3517168,Pokhishchennyy transformerami,"A., Sergey",745,6.8,director,7.384375
27,3523090,Poteryannaya plyonka,"A., Sergey",745,7.0,director,7.384375
28,3546679,Rage of Spirits,"A., Sergey",745,7.2,director,7.384375
29,3550928,Raukhenek,"A., Sergey",745,7.1,director,7.384375
...,...,...,...,...,...,...,...
263501,1861920,Taraji P. Henson/Mumford & Sons,"Seidell, Streeter",2003577,5.8,writer,7.400000
263502,1861937,Tina Fey & Amy Poehler/Bruce Springsteen and t...,"Seidell, Streeter",2003577,8.1,writer,7.400000
263503,1861960,Tracy Morgan/Demi Lovato,"Seidell, Streeter",2003577,7.8,writer,7.400000
263504,1861320,Chris Hemsworth/Chance The Rapper,"Sirus, Dave",2060059,6.5,writer,7.733333
263505,1861421,Elizabeth Banks/Disclosure,"Sirus, Dave",2060059,7.2,writer,7.733333
263506,1861711,Matthew McConaughey/Adele,"Sirus, Dave",2060059,7.5,writer,7.733333
263507,1861742,Miley Cyrus,"Sirus, Dave",2060059,6.3,writer,7.733333
263508,1861850,Ryan Gosling/Leon Bridges,"Sirus, Dave",2060059,8.0,writer,7.733333
263509,1861937,Tina Fey & Amy Poehler/Bruce Springsteen and t...,"Sirus, Dave",2060059,8.1,writer,7.733333
263510,1861960,Tracy Morgan/Demi Lovato,"Sirus, Dave",2060059,7.8,writer,7.733333
263511,3880123,Un homme au pair,"Dussaux, Laurent",610475,6.1,writer,5.700000
263512,3446689,Norjmaa,Bayaneruul,157759,7.4,writer,7.300000
263513,3446689,Norjmaa,Bayaneruul,157759,7.4,writer,7.300000
263514,2813505,Bai niao chao feng,"Wu, Tian-Ming",2428191,7.2,writer,7.066667
263515,2906388,Chuang ru zhe,"Wang, Xiaoshuai",2347167,6.8,writer,6.750000
263516,3115042,Goliyon Ki Rasleela Ram-Leela,"Bhansali, Sanjay Leela",197750,6.3,writer,8.200000
263517,3134879,Happy Ending,"D.K., Krishna",489037,5.5,writer,6.800000
263518,3511815,PK,"Hirani, Rajkumar",964114,8.2,writer,8.066667
263519,3595644,Satyagraha,"Jha, Prakash",1064337,6.0,writer,6.500000
263520,3134879,Happy Ending,"Nidimoru, Raj",1605227,5.5,writer,8.100000
263521,2787388,Any Body Can Dance 2,Remo,1840550,5.6,writer,5.525000
263522,3695439,Tanu Weds Manu Returns,"Sharma, Himanshu",2021573,7.8,writer,8.750000
263523,3056679,Familywala,"Vora, Neeraj",2326663,6.0,writer,5.666667
263524,3056679,Familywala,"Vora, Neeraj",2326663,6.0,writer,5.666667
263525,3057240,Fantasia,"Wang, Chao",2346020,5.5,writer,3.400000
263526,2681401,Zhao shi gu er an,"Chen, Wengui",386917,7.2,writer,6.066667
263527,3621063,Shen qi,"Hu, Sherwood",996338,4.6,writer,4.400000
263528,3645316,Soi yat hei,"Lo, Yiu Fai",1308302,4.4,writer,6.600000
263529,3621063,Shen qi,"Tsang, Kan-Cheung",2250259,4.6,writer,6.950000
263530,3949171,Xin hua lu fang,"Yue, Xiaojun",2450701,6.4,writer,6.180000

In [9]:
movies.rating=movies.rating.astype(float)
# actors.person_id=actors.person_id.astype(str)

In [10]:
pivot_table = pd.pivot_table(movies, index=['movie_id', 'role'],
                                     values=['movie_name', 'name', 'person_id', 'rating', 'role'],
                                     aggfunc=[lambda x: ' - '.join(x), np.mean]).reset_index()

In [11]:
pivot_table

       movie_id      role                                           <lambda>  \
                                                                  movie_name
0            11  director                                     #15SecondScare
1            71     actor                                    #ATown - #ATown
2            71   actress                           #ATown - #ATown - #ATown
3            71  director                                             #ATown
4            71    writer                                    #ATown - #ATown
5            92    writer                                #Besties - #Besties
6           151  director                                          #Cybriety
7           151    writer                                          #Cybriety
8           195   actress        #Hashtag: The Series - #Hashtag: The Series
9           973  director                                       $5,000 Video
10          973    writer                                       $5,000 Video
11         2645  director                                    1 Minute Horror
12         2645    writer                                    1 Minute Horror
13         3543  director                                       Civil Rights
14         3544     actor                                     Edison & Tesla
15         3544  director                                     Edison & Tesla
16         3548     actor                                          Las Vegas
17         3549     actor                                          Marijuana
18         3550     actor                                              Money
19         3550  director                                              Money
20         3552  director                        Presidential Assassinations
21         3553  director                                        Prohibition
22         3554     actor                                              Texas
23         3554  director                                              Texas
24         3555  director                            The American Revolution
25         3556     actor                                           The Flag
26         3557  director                               The Founding Fathers
27         3558     actor                                      The Gold Rush
28         3559     actor                                     The Hoover Dam
29         3564  director                                    The White House
...         ...       ...                                                ...
144033  3970980   actress                                       �verliggaren
144034  3970980    writer                        �verliggaren - �verliggaren
144035  3970986     actor                                �yle sevdim ki seni
144036  3970986   actress                                �yle sevdim ki seni
144037  3970987  director                                   �yle ya da B�yle
144038  3971062  director                                       �jratervez�s
144039  3971062    writer                        �jratervez�s - �jratervez�s
144040  3971085     actor                                 �ltima Transmisi�n
144041  3971085   actress  �ltima Transmisi�n - �ltima Transmisi�n - �lti...
144042  3971195     actor                                �ber den Tag hinaus
144043  3971195   actress  �ber den Tag hinaus - �ber den Tag hinaus - �b...
144044  3971195    writer                                �ber den Tag hinaus
144045  3971203  director                                     �ber die Jahre
144046  3971203    writer                    �ber die Jahre - �ber die Jahre
144047  3971226     actor  �ber-Ich und Du - �ber-Ich und Du - �ber-Ich u...
144048  3971226   actress                                    �ber-Ich und Du
144049  3971226  director                                    �ber-Ich und Du
144050  3971226    writer                                    �ber-Ich und Du
144051  3971247     actor  �berleben an der Scheidungsfront - �berleben a...
144052  3971247   actress  �berleben an der Scheidungsfront - �berleben a...
144053  3971247  director                   �berleben an der Scheidungsfront
144054  3971260     actor            �bermansion - �bermansion - �bermansion
144055  3971260   actress                                        �bermansion
144056  3971260    writer                                        �bermansion
144057  3971396     actor                      �etta Reddast - �etta Reddast
144058  3971396   actress                                      �etta Reddast
144059  3971398     actor                                  �restir - �restir
144060  3971398   actress                                            �restir
144061  3971410  director                                             �rtico
144062  3971410    writer                                             �rtico

                                                                      mean  \
                                                     name avg_actor_rating
0                                           Andr�, Daniel         5.200000
1                               Babb, Derek - Babb, Derek         4.800000
2        Larson, Mallory - Weinberg, Elena - Koehler, Ivy         5.588889
3                                             Coe, Duncan         5.800000
4                       Larson, Mallory - Weinberg, Elena         4.433333
5                 Finklea, Carrie - Johnson, Nicole Marie         5.279167
6                                           Silver, Blake         6.207143
7                                        Ruddy, Alexandra         6.575000
8                      Alton, Marnie - Black-Spence, Kate         5.798485
9                                        Buress, Hannibal         7.033333
10                                       Buress, Hannibal         7.033333
11                                           Leary, Shane         5.300000
12                                           Leary, Shane         5.300000
13                                          Chait, Stuart         8.300000
14                                         Rollins, Henry         6.950794
15                                          Chait, Stuart         8.300000
16                                         Rollins, Henry         6.950794
17                                         Rollins, Henry         6.950794
18                                         Rollins, Henry         6.950794
19                                          Chait, Stuart         8.300000
20                                          Chait, Stuart         8.300000
21                                          Chait, Stuart         8.300000
22                                         Rollins, Henry         6.950794
23                                          Chait, Stuart         8.300000
24                                          Chait, Stuart         8.300000
25                                         Rollins, Henry         6.950794
26                                          Chait, Stuart         8.300000
27                                         Rollins, Henry         6.950794
28                                         Rollins, Henry         6.950794
29                                          Chait, Stuart         8.300000
...                                                   ...              ...
144033                                   Nilsson, Isabell         8.500000
144034                   Jakobsson, Dan - J�nsson, Niklas         7.000000
144035                                      G�rsoy, Oktay         4.650000
144036                                       Terzic, Alma         6.325000
144037                                        Kaya, Alper         3.300000
144038                                     T�th, Barnab�s         6.390909
144039                    T�th, Barnab�s - T�th, Barnab�s         6.390909
144040                                      Casette, Rafa         5.590000
144041    Messa, Alba - Arag�n, M�nica - Blanco, Estrella         3.276190
144042                                  Sachtleben, Horst         6.193750
144043  Studt, Katja - Schwab, Charlotte - Schorn, Chr...         6.514114
144044                                       Leesch, Edda         5.850000
144045                               Geyrhalter, Nikolaus         9.000000
144046        Geyrhalter, Nikolaus - Widerhofer, Wolfgang         8.525000
144047  Friedrich, Georg - Wilms, Andr� - Wackerbarth,...         6.323440
144048                                     Walker, Saskia         5.900000
144049                               Heisenberg, Benjamin         6.650000
144050                               Heisenberg, Benjamin         6.650000
144051                    Ochsenknecht, Uwe - Bang, Claes         5.871299
144052              Niehaus, Valerie - Gr�schel, Cornelia         6.116667
144053                                       Selge, Titus         8.200000
144054    Cranston, Bryan - Gilmore, Tucker - Green, Seth         6.785233
144055                                     Gardner, Heidi         7.400000
144056                                  Senreich, Matthew         7.650000
144057           Thors, Bj�rn - Sigur�sson, Ingvar Eggert         6.222381
144058                              Bj�rgvinsd�ttir, Edda         6.218182
144059  Sigur�sson, Ingvar Eggert - Fjalarsson, Atli O...         6.927381
144060                                  Kjeld, Kristbj�rg         6.068421
144061                                 Vel�zquez, Gabriel         4.300000
144062                                 Vel�zquez, Gabriel         4.300000


           person_id rating
0       6.687900e+04    6.7
1       1.102890e+05    9.2
2       3.351342e+06    9.2
3       4.216420e+05    9.2
4       3.467087e+06    9.2
5       2.961118e+06    5.6
6       2.047639e+06    6.7
7       3.532598e+06    6.7
8       2.549198e+06    7.1
9       2.991540e+05    6.3
10      2.991540e+05    6.3
11      1.257734e+06    6.6
12      1.257734e+06    6.6
13      3.712170e+05    7.5
14      1.892473e+06    7.5
15      3.712170e+05    7.5
16      1.892473e+06    7.4
17      1.892473e+06    8.4
18      1.892473e+06    7.7
19      3.712170e+05    7.7
20      3.712170e+05    8.3
21      3.712170e+05    8.1
22      1.892473e+06    7.5
23      3.712170e+05    7.5
24      3.712170e+05    7.7
25      1.892473e+06    7.8
26      3.712170e+05    7.4
27      1.892473e+06    7.6
28      1.892473e+06    7.6
29      3.712170e+05    7.6
...              ...    ...
144033  3.366812e+06    8.5
144034  1.072101e+06    8.5
144035  8.763770e+05    5.3
144036  3.687723e+06    5.3
144037  1.126104e+06    5.2
144038  2.263865e+06    8.1
144039  2.263865e+06    8.1
144040  3.545600e+05    1.5
144041  2.803191e+06    1.5
144042  1.933284e+06    7.8
144043  3.599947e+06    7.8
144044  3.171448e+06    7.8
144045  7.874950e+05    8.1
144046  1.586715e+06    8.1
144047  1.823403e+06    5.9
144048  3.764046e+06    5.9
144049  9.351750e+05    5.9
144050  9.351750e+05    5.9
144051  8.846370e+05    7.4
144052  3.155575e+06    7.4
144053  2.005389e+06    7.4
144054  7.024627e+05    7.2
144055  2.898205e+06    7.2
144056  2.008648e+06    7.2
144057  2.129703e+06    4.6
144058  2.593705e+06    4.6
144059  1.373120e+06    7.0
144060  3.113425e+06    7.0
144061  2.301416e+06    7.1
144062  2.301416e+06    7.1

[144063 rows x 7 columns]

In [12]:
pivot_table.columns=pivot_table.columns.droplevel(1)
pivot_table.columns=['movie_id','role','movie_name','name','avg_actor_rating','person_id','movie_rating']

In [13]:
pivot_table

,movie_id,role,movie_name,name,avg_actor_rating,person_id,movie_rating
0,11,director,#15SecondScare,"Andr�, Daniel",5.200000,6.687900e+04,6.7
1,71,actor,#ATown - #ATown,"Babb, Derek - Babb, Derek",4.800000,1.102890e+05,9.2
2,71,actress,#ATown - #ATown - #ATown,"Larson, Mallory - Weinberg, Elena - Koehler, Ivy",5.588889,3.351342e+06,9.2
3,71,director,#ATown,"Coe, Duncan",5.800000,4.216420e+05,9.2
4,71,writer,#ATown - #ATown,"Larson, Mallory - Weinberg, Elena",4.433333,3.467087e+06,9.2
5,92,writer,#Besties - #Besties,"Finklea, Carrie - Johnson, Nicole Marie",5.279167,2.961118e+06,5.6
6,151,director,#Cybriety,"Silver, Blake",6.207143,2.047639e+06,6.7
7,151,writer,#Cybriety,"Ruddy, Alexandra",6.575000,3.532598e+06,6.7
8,195,actress,#Hashtag: The Series - #Hashtag: The Series,"Alton, Marnie - Black-Spence, Kate",5.798485,2.549198e+06,7.1
9,973,director,"$5,000 Video","Buress, Hannibal",7.033333,2.991540e+05,6.3
10,973,writer,"$5,000 Video","Buress, Hannibal",7.033333,2.991540e+05,6.3
11,2645,director,1 Minute Horror,"Leary, Shane",5.300000,1.257734e+06,6.6
12,2645,writer,1 Minute Horror,"Leary, Shane",5.300000,1.257734e+06,6.6
13,3543,director,Civil Rights,"Chait, Stuart",8.300000,3.712170e+05,7.5
14,3544,actor,Edison & Tesla,"Rollins, Henry",6.950794,1.892473e+06,7.5
15,3544,director,Edison & Tesla,"Chait, Stuart",8.300000,3.712170e+05,7.5
16,3548,actor,Las Vegas,"Rollins, Henry",6.950794,1.892473e+06,7.4
17,3549,actor,Marijuana,"Rollins, Henry",6.950794,1.892473e+06,8.4
18,3550,actor,Money,"Rollins, Henry",6.950794,1.892473e+06,7.7
19,3550,director,Money,"Chait, Stuart",8.300000,3.712170e+05,7.7
20,3552,director,Presidential Assassinations,"Chait, Stuart",8.300000,3.712170e+05,8.3
21,3553,director,Prohibition,"Chait, Stuart",8.300000,3.712170e+05,8.1
22,3554,actor,Texas,"Rollins, Henry",6.950794,1.892473e+06,7.5
23,3554,director,Texas,"Chait, Stuart",8.300000,3.712170e+05,7.5
24,3555,director,The American Revolution,"Chait, Stuart",8.300000,3.712170e+05,7.7
25,3556,actor,The Flag,"Rollins, Henry",6.950794,1.892473e+06,7.8
26,3557,director,The Founding Fathers,"Chait, Stuart",8.300000,3.712170e+05,7.4
27,3558,actor,The Gold Rush,"Rollins, Henry",6.950794,1.892473e+06,7.6
28,3559,actor,The Hoover Dam,"Rollins, Henry",6.950794,1.892473e+06,7.6
29,3564,director,The White House,"Chait, Stuart",8.300000,3.712170e+05,7.6
...,...,...,...,...,...,...,...
144033,3970980,actress,�verliggaren,"Nilsson, Isabell",8.500000,3.366812e+06,8.5
144034,3970980,writer,�verliggaren - �verliggaren,"Jakobsson, Dan - J�nsson, Niklas",7.000000,1.072101e+06,8.5
144035,3970986,actor,�yle sevdim ki seni,"G�rsoy, Oktay",4.650000,8.763770e+05,5.3
144036,3970986,actress,�yle sevdim ki seni,"Terzic, Alma",6.325000,3.687723e+06,5.3
144037,3970987,director,�yle ya da B�yle,"Kaya, Alper",3.300000,1.126104e+06,5.2
144038,3971062,director,�jratervez�s,"T�th, Barnab�s",6.390909,2.263865e+06,8.1
144039,3971062,writer,�jratervez�s - �jratervez�s,"T�th, Barnab�s - T�th, Barnab�s",6.390909,2.263865e+06,8.1
144040,3971085,actor,�ltima Transmisi�n,"Casette, Rafa",5.590000,3.545600e+05,1.5
144041,3971085,actress,�ltima Transmisi�n - �ltima Transmisi�n - �lti...,"Messa, Alba - Arag�n, M�nica - Blanco, Estrella",3.276190,2.803191e+06,1.5
144042,3971195,actor,�ber den Tag hinaus,"Sachtleben, Horst",6.193750,1.933284e+06,7.8
144043,3971195,actress,�ber den Tag hinaus - �ber den Tag hinaus - �b...,"Studt, Katja - Schwab, Charlotte - Schorn, Chr...",6.514114,3.599947e+06,7.8
144044,3971195,writer,�ber den Tag hinaus,"Leesch, Edda",5.850000,3.171448e+06,7.8
144045,3971203,director,�ber die Jahre,"Geyrhalter, Nikolaus",9.000000,7.874950e+05,8.1
144046,3971203,writer,�ber die Jahre - �ber die Jahre,"Geyrhalter, Nikolaus - Widerhofer, Wolfgang",8.525000,1.586715e+06,8.1
144047,3971226,actor,�ber-Ich und Du - �ber-Ich und Du - �ber-Ich u...,"Friedrich, Georg - Wilms, Andr� - Wackerbarth,...",6.323440,1.823403e+06,5.9
144048,3971226,actress,�ber-Ich und Du,"Walker, Saskia",5.900000,3.764046e+06,5.9
144049,3971226,director,�ber-Ich und Du,"Heisenberg, Benjamin",6.650000,9.351750e+05,5.9
144050,3971226,writer,�ber-Ich und Du,"Heisenberg, Benjamin",6.650000,9.351750e+05,5.9
144051,3971247,actor,�berleben an der Scheidungsfront - �berleben a...,"Ochsenknecht, Uwe - Bang, Claes",5.871299,8.846370e+05,7.4
144052,3971247,actress,�berleben an der Scheidungsfront - �berleben a...,"Niehaus, Valerie - Gr�schel, Cornelia",6.116667,3.155575e+06,7.4
144053,3971247,director,�berleben an der Scheidungsfront,"Selge, Titus",8.200000,2.005389e+06,7.4
144054,3971260,actor,�bermansion - �bermansion - �bermansion,"Cranston, Bryan - Gilmore, Tucker - Green, Seth",6.785233,7.024627e+05,7.2
144055,3971260,actress,�bermansion,"Gardner, Heidi",7.400000,2.898205e+06,7.2
144056,3971260,writer,�bermansion,"Senreich, Matthew",7.650000,2.008648e+06,7.2
144057,3971396,actor,�etta Reddast - �etta Reddast,"Thors, Bj�rn - Sigur�sson, Ingvar Eggert",6.222381,2.129703e+06,4.6
144058,3971396,actress,�etta Reddast,"Bj�rgvinsd�ttir, Edda",6.218182,2.593705e+06,4.6
144059,3971398,actor,�restir - �restir,"Sigur�sson, Ingvar Eggert - Fjalarsson, Atli O...",6.927381,1.373120e+06,7.0
144060,3971398,actress,�restir,"Kjeld, Kristbj�rg",6.068421,3.113425e+06,7.0
144061,3971410,director,�rtico,"Vel�zquez, Gabriel",4.300000,2.301416e+06,7.1
144062,3971410,writer,�rtico,"Vel�zquez, Gabriel",4.300000,2.301416e+06,7.1

In [15]:
del pivot_table['person_id']

In [16]:
pivot_table

,movie_id,role,movie_name,name,avg_actor_rating,movie_rating
0,11,director,#15SecondScare,"Andr�, Daniel",5.200000,6.7
1,71,actor,#ATown - #ATown,"Babb, Derek - Babb, Derek",4.800000,9.2
2,71,actress,#ATown - #ATown - #ATown,"Larson, Mallory - Weinberg, Elena - Koehler, Ivy",5.588889,9.2
3,71,director,#ATown,"Coe, Duncan",5.800000,9.2
4,71,writer,#ATown - #ATown,"Larson, Mallory - Weinberg, Elena",4.433333,9.2
5,92,writer,#Besties - #Besties,"Finklea, Carrie - Johnson, Nicole Marie",5.279167,5.6
6,151,director,#Cybriety,"Silver, Blake",6.207143,6.7
7,151,writer,#Cybriety,"Ruddy, Alexandra",6.575000,6.7
8,195,actress,#Hashtag: The Series - #Hashtag: The Series,"Alton, Marnie - Black-Spence, Kate",5.798485,7.1
9,973,director,"$5,000 Video","Buress, Hannibal",7.033333,6.3
10,973,writer,"$5,000 Video","Buress, Hannibal",7.033333,6.3
11,2645,director,1 Minute Horror,"Leary, Shane",5.300000,6.6
12,2645,writer,1 Minute Horror,"Leary, Shane",5.300000,6.6
13,3543,director,Civil Rights,"Chait, Stuart",8.300000,7.5
14,3544,actor,Edison & Tesla,"Rollins, Henry",6.950794,7.5
15,3544,director,Edison & Tesla,"Chait, Stuart",8.300000,7.5
16,3548,actor,Las Vegas,"Rollins, Henry",6.950794,7.4
17,3549,actor,Marijuana,"Rollins, Henry",6.950794,8.4
18,3550,actor,Money,"Rollins, Henry",6.950794,7.7
19,3550,director,Money,"Chait, Stuart",8.300000,7.7
20,3552,director,Presidential Assassinations,"Chait, Stuart",8.300000,8.3
21,3553,director,Prohibition,"Chait, Stuart",8.300000,8.1
22,3554,actor,Texas,"Rollins, Henry",6.950794,7.5
23,3554,director,Texas,"Chait, Stuart",8.300000,7.5
24,3555,director,The American Revolution,"Chait, Stuart",8.300000,7.7
25,3556,actor,The Flag,"Rollins, Henry",6.950794,7.8
26,3557,director,The Founding Fathers,"Chait, Stuart",8.300000,7.4
27,3558,actor,The Gold Rush,"Rollins, Henry",6.950794,7.6
28,3559,actor,The Hoover Dam,"Rollins, Henry",6.950794,7.6
29,3564,director,The White House,"Chait, Stuart",8.300000,7.6
...,...,...,...,...,...,...
144033,3970980,actress,�verliggaren,"Nilsson, Isabell",8.500000,8.5
144034,3970980,writer,�verliggaren - �verliggaren,"Jakobsson, Dan - J�nsson, Niklas",7.000000,8.5
144035,3970986,actor,�yle sevdim ki seni,"G�rsoy, Oktay",4.650000,5.3
144036,3970986,actress,�yle sevdim ki seni,"Terzic, Alma",6.325000,5.3
144037,3970987,director,�yle ya da B�yle,"Kaya, Alper",3.300000,5.2
144038,3971062,director,�jratervez�s,"T�th, Barnab�s",6.390909,8.1
144039,3971062,writer,�jratervez�s - �jratervez�s,"T�th, Barnab�s - T�th, Barnab�s",6.390909,8.1
144040,3971085,actor,�ltima Transmisi�n,"Casette, Rafa",5.590000,1.5
144041,3971085,actress,�ltima Transmisi�n - �ltima Transmisi�n - �lti...,"Messa, Alba - Arag�n, M�nica - Blanco, Estrella",3.276190,1.5
144042,3971195,actor,�ber den Tag hinaus,"Sachtleben, Horst",6.193750,7.8
144043,3971195,actress,�ber den Tag hinaus - �ber den Tag hinaus - �b...,"Studt, Katja - Schwab, Charlotte - Schorn, Chr...",6.514114,7.8
144044,3971195,writer,�ber den Tag hinaus,"Leesch, Edda",5.850000,7.8
144045,3971203,director,�ber die Jahre,"Geyrhalter, Nikolaus",9.000000,8.1
144046,3971203,writer,�ber die Jahre - �ber die Jahre,"Geyrhalter, Nikolaus - Widerhofer, Wolfgang",8.525000,8.1
144047,3971226,actor,�ber-Ich und Du - �ber-Ich und Du - �ber-Ich u...,"Friedrich, Georg - Wilms, Andr� - Wackerbarth,...",6.323440,5.9
144048,3971226,actress,�ber-Ich und Du,"Walker, Saskia",5.900000,5.9
144049,3971226,director,�ber-Ich und Du,"Heisenberg, Benjamin",6.650000,5.9
144050,3971226,writer,�ber-Ich und Du,"Heisenberg, Benjamin",6.650000,5.9
144051,3971247,actor,�berleben an der Scheidungsfront - �berleben a...,"Ochsenknecht, Uwe - Bang, Claes",5.871299,7.4
144052,3971247,actress,�berleben an der Scheidungsfront - �berleben a...,"Niehaus, Valerie - Gr�schel, Cornelia",6.116667,7.4
144053,3971247,director,�berleben an der Scheidungsfront,"Selge, Titus",8.200000,7.4
144054,3971260,actor,�bermansion - �bermansion - �bermansion,"Cranston, Bryan - Gilmore, Tucker - Green, Seth",6.785233,7.2
144055,3971260,actress,�bermansion,"Gardner, Heidi",7.400000,7.2
144056,3971260,writer,�bermansion,"Senreich, Matthew",7.650000,7.2
144057,3971396,actor,�etta Reddast - �etta Reddast,"Thors, Bj�rn - Sigur�sson, Ingvar Eggert",6.222381,4.6
144058,3971396,actress,�etta Reddast,"Bj�rgvinsd�ttir, Edda",6.218182,4.6
144059,3971398,actor,�restir - �restir,"Sigur�sson, Ingvar Eggert - Fjalarsson, Atli O...",6.927381,7.0
144060,3971398,actress,�restir,"Kjeld, Kristbj�rg",6.068421,7.0
144061,3971410,director,�rtico,"Vel�zquez, Gabriel",4.300000,7.1
144062,3971410,writer,�rtico,"Vel�zquez, Gabriel",4.300000,7.1

In [17]:
t=pivot_table.iloc[0:8]
t

,movie_id,role,movie_name,name,avg_actor_rating,movie_rating
0,11,director,#15SecondScare,"Andr�, Daniel",5.200000,6.7
1,71,actor,#ATown - #ATown,"Babb, Derek - Babb, Derek",4.800000,9.2
2,71,actress,#ATown - #ATown - #ATown,"Larson, Mallory - Weinberg, Elena - Koehler, Ivy",5.588889,9.2
3,71,director,#ATown,"Coe, Duncan",5.800000,9.2
4,71,writer,#ATown - #ATown,"Larson, Mallory - Weinberg, Elena",4.433333,9.2
5,92,writer,#Besties - #Besties,"Finklea, Carrie - Johnson, Nicole Marie",5.279167,5.6
6,151,director,#Cybriety,"Silver, Blake",6.207143,6.7
7,151,writer,#Cybriety,"Ruddy, Alexandra",6.575000,6.7

In [ ]:
s=pd.pivot_table(t, 
               index=['movie_id','movie_name','movie_rating'], 
               columns="role",
                 aggfunc=lambda x: ' - '.join(x)).reset_index()

In [ ]:
s.columns=s.columns.droplevel(1)

In [ ]:
s.columns=['movie_id','movie_name','id'	movie_rating,actor	actress	director	writer]

In [ ]:
s

In [ ]:
ia = IMDb('sql', uri='mysql://imdb:imdb@localhost/imdb')

In [ ]:
movies=ia.search_movie(title="*", production_year=2012,results=1000)

In [ ]:
len(movies)

In [ ]:
first_match=movies[999]

In [ ]:
first_match.summary()

In [ ]:
ia.update(first_match, 'all')

In [ ]:
print first_match.summary()

In [ ]:
ia.get_movie('0133093')

In [ ]:
chicago_search=ia.search_keyword(u'alabama')

In [ ]:
s_result=ia.search_movie('die hard')

In [ ]:
for item in s_result:
    print item['long imdb canonical title'], item.movieID

In [ ]:
the_unt = s_result[0]

In [ ]:
ia.update(the_unt)

In [ ]:
print the_unt['runtime']

In [ ]:
print the_unt['rating']

In [ ]:
director = the_unt['director']
director.

In [ ]:
ia.search_movie()

In [ ]:
m = ia.get_movie('2981449')

In [ ]:
m.data